### ISSUE TITLE
Broadcast the Reduce results into the `RegTile`.

### ISSUE THREAD

**Issue by KuangjuX** [TiledTensor/TiledCUDA#107]
The current shape of the reduce result on the `RegTile` is inconsistent with the shape of the `RegTile` itself. This has created difficulties in performing computations between these two different shapes (this would require a lot of redundant code to handle the shape differences). Therefore, I hope to keep the reduce result on the original `RegTile`, so that the `RegTile` can maintain a consistent shape to perform the computations.

I will give an example to illustrate the necessity of this form:

```cpp
// Execute reduce operation.
compute::MaxReduce<SrcReduceTile, kLayout> row_max;
// accumulate onto the max_vec
row_max(attn_block, max_vec);

__syncthreads();

// subtract max from flashattention -- now all <= 0.
compute::RegSubReduceTile<SrcReduceTile, kLayout> sub_max;
sub_max(attn_block, max_vec);
```

In this example, we first perform a reduce operation to compute the maximum value of each row, and then subtract the reduced maximum values from the `attn_block`. However, since the shapes of the two tiles (`attn_block` and the reduced result) are different, we have to implement different computation methods for the two different shapes, which will lead to additional code complexity.

Therefore, this will lead to different combination scenarios, and it will not be possible to implement it with just a single implementation for two identical shapes. Therefore, I feel that storing the Reduce result in the same format as the `BaseTile` might be a better choice. However, this could potentially increase the memory pressure.

I would very much like to get your advice. @haruhi55

**Comment by haruhi55** [comment]
Adding broadcasting as an explicit looping mechanism might be a solution worth trying.
