### ISSUE TITLE
Rename `SharedTileIterator` to `TileIterator` to reduce redundancy

### ISSUE THREAD

**Issue by haruhi55** [TiledTensor/TiledCUDA#85]
TileIterator works for both global memory tiles and shared memory tiles. There is no significant difference between these two, as both are contiguous memory compared to distributed thread-local register files.

Therefore, shall we rename [`SharedTileIterator`](https://github.com/TiledTensor/TiledCUDA/blob/master/include/types/tile_iterator.hpp#L22) to `TileIterator` to simplify the concept?

**Comment by KuangjuX** [comment]
Agreed, we can rename `SharedTileIterator` to `TileIterator` so that it can be used for both Global and Shared memory.

**Comment by haruhi55** [comment]
Let me make this change.
